server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://postgres@localhost:5432/microservices
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
web:
  service:
    client:
      url: http://localhost:8080/test_soap/endpoint1